import { GraphQLResolveInfo, GraphQLScalarType } from 'graphql';
/**
 * This file is auto-generated by @pongsatt/graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  product?: GQLProduct;
  products?: (GQLProduct | null)[];
}

export interface GQLProduct {
  id: string;
  name: string;
  description?: string;
  createdDate: GQLDate;
}

export type GQLDate = any;

export interface GQLMutation {
  addProduct?: (GQLProduct | null)[];
}

export interface GQLProductInput {
  name: string;
  description?: string;
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver;
  Product?: GQLProductTypeResolver;
  Date?: GraphQLScalarType;
  Mutation?: GQLMutationTypeResolver;
}
export interface GQLQueryTypeResolver<TParent = any> {
  product?: QueryToProductResolver<TParent>;
  products?: QueryToProductsResolver<TParent>;
}

export interface QueryToProductArgs {
  id?: string;
}
export interface QueryToProductResolver<TParent = any, TResult = GQLProduct|Promise<GQLProduct>> {
  (parent: TParent, args: QueryToProductArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToProductsResolver<TParent = any, TResult = Array<GQLProduct>|Promise<Array<GQLProduct>>> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLProductTypeResolver<TParent = any> {
  id?: ProductToIdResolver<TParent>;
  name?: ProductToNameResolver<TParent>;
  description?: ProductToDescriptionResolver<TParent>;
  createdDate?: ProductToCreatedDateResolver<TParent>;
}

export interface ProductToIdResolver<TParent = any, TResult = string|Promise<string>> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProductToNameResolver<TParent = any, TResult = string|Promise<string>> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProductToDescriptionResolver<TParent = any, TResult = string|Promise<string>> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProductToCreatedDateResolver<TParent = any, TResult = GQLDate|Promise<GQLDate>> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLMutationTypeResolver<TParent = any> {
  addProduct?: MutationToAddProductResolver<TParent>;
}

export interface MutationToAddProductArgs {
  product: GQLProductInput;
}
export interface MutationToAddProductResolver<TParent = any, TResult = Array<GQLProduct>|Promise<Array<GQLProduct>>> {
  (parent: TParent, args: MutationToAddProductArgs, context: any, info: GraphQLResolveInfo): TResult;
}
